### ISSUE TITLE
IPCs are overpowered

### ISSUE THREAD

**Issue by Just-a-Unity-Dev** [ekrixi-14/ekrixi#142]
They have the metallic damage modifier set which makes punches to them just not work in general

![image](https://github.com/ekrixi-14/ekrixi/assets/67359748/afd0a1e0-a872-4961-bd81-389b7d14c003)

With this damage set they infact die *slower* in space, they can also easily robust spirates (which is a wow)

all in all IPCs need their damage modifier set swapped with something else, and their code needs to be updated with proper upstream bases

**Comment by dvir001** [comment]
Keep in mind if im adding Ion storm event you going to have IPC running around the ship as the moment they get hit they die on the spot.

**Comment by Just-a-Unity-Dev** [comment]
Fixed in #289
