### ISSUE TITLE
How to give command whitelist

### ISSUE THREAD

**Issue by Iced-Coded** [ekrixi-14/ekrixi#158]
I mean, I have full access on my build, but, how do I give command roles whitelist?

**Comment by Just-a-Unity-Dev** [comment]
You can use the `playtime_addrole` for `JobEkrixiWhitelist`, that or disable the `game.role_timers` CVAR to give yourself access to command locked role. Otherwise, if you mean *giving a role whitelist*, you can take a look at `captain.yml` under `requirements`.
