### ISSUE TITLE
The Warpening: An Overhaul of FTL

### ISSUE THREAD

**Issue by Just-a-Unity-Dev** [ekrixi-14/ekrixi#159]
The Warpening should have 4 core mechanics which I will describe here.

# Spin Console
The console which allows you to graphically see all points and sectors. See NSV-13, Shiptest, etc.

# Spin Drive
The physical spin drive, insert a crystal, will dry out after 100 or so warps, so a full 5 rounds or so. Will take 1 minute to boot a drive. Realistically they would be a single entity where you would click them to "prime", then they'd take a minute to load then you could warp. If you want to speed it up, you can do some basic algebra.

Spinavi crystals will have an integrity, codewise will be at 0 (100%) and cap out at 100 (0% integrity)

Integrity affects how far your ship can go based on it's integrity (100% would be 100% effectiveness, 50% would be 150%, etc), and warping degrades your integrity by a random amount
Above 50% integrity is the "stable zone", there is a 0% chance that the crystal will explode
Within 49-15% integrity is the caution zone, a 20% chance that the crystal will explode
Everything below 15% is the danger zone, a 40% chance that the crystal will explode
The crystal will explode automatically at 0% creating a blast around the size of a 53mm-104mm? or a SAM explosion maybe

The crystal will degrade by 1-7% every warp. Each crystal regardless of integrity will cost 10,000 credits.

The lower the crystal integrity, the further range it goes, because the more "unstable" a crystal is, the more crayzy it is.

# Points And Sectors
All "points" are now stars. Solars can only work in stars, you can no longer directly warp to planets without being at the star first, but visiting planets does not require a drive spin either

Sectors are essentially a star cluster, enter a Gateway point to jump between sectors. Whilst spin drives can only get you so far, getting further requires you to find a gateway. You can do this either by exploring or looting ruins.

# Gateways & Hostile Generation Points
The longer you spend in a sector, HGPs will produce ships to look, find, and hunt for you. Approximately 3 ships per 1 J-tick (5 minutes), so around 36 ships per hour. These ships will be random and depend on the faction's HGP, however the longer you spend in a sector, the more dangerously populated the sectors get. This is where gateways come in.

Gateways are essentially Crescent's fuckin relays and shit (this is deep lore), you can only go so far with spin drives but going further requires a gateway. Essentially two gates linked together to accelerate ships at faster than light speeds, AKA literally a fucking mass effect relay. MIC DROP.

**Comment by dvir001** [comment]
You can make it into a Toggle for the grid component that allow to FTL

Just add a timer to it to toggle it on, and toggle off after an FTL.

**Comment by Just-a-Unity-Dev** [comment]
Requires rewriting
