### ISSUE TITLE
Need a way to compress shuttles

### ISSUE THREAD

**Issue by Just-a-Unity-Dev** [ekrixi-14/ekrixi#161]
I honestly have no idea how to even "sell" a ship, do we send it as an item? How the fuck does that work???

**Comment by dvir001** [comment]
You run a a calc on the grid to grab all the items on it with how much they are worth, then you hand out the price of the grid back to cargo bank or as cash on the floor and delete the grid

Code exists on Frontier fork if you want to grab it.

**Comment by Just-a-Unity-Dev** [comment]
I don't mean "how much do we price a ship", more rather "how do we spawn the grid to players"

**Comment by Blackern5000** [comment]
I believe the code for that is on frontier as well

**Comment by Just-a-Unity-Dev** [comment]
Ekrixi issue
